# Default SearXNG settings
use_default_settings: true
server:
  secret_key: "ultrasecretkey" # Overridden by SEARXNG_SECRET env var
  limiter: false
  image_proxy: true
  bind_address: "0.0.0.0"
  port: 8080

engines:
  - name: google
    engine: google
    shortcut: g
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
  - name: bing
    engine: bing
    shortcut: b
